name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: yarn install
        run: |
          yarn install
      - name: test
        run: |
          yarn test
